[plugin]
class = "io.ballerina.stdlib.mi.plugin.MICompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/mi-compiler-plugin-0.1.0-SNAPSHOT.jar"

[[dependency]]
path = "build/antlr4-runtime-4.5.1-1.jar"

[[dependency]]
path = "build/handlebars-4.0.6.jar"
